
"""Add image_filename to Profile

Revision ID: 797f6b03548d
Revises: c1f6ba11076e
Create Date: 2025-05-11 18:51:17.133668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '797f6b03548d'
down_revision = 'c1f6ba11076e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###


