
"""Add Comment model with named FK

Revision ID: ca817d3dfeca
Revises: 797f6b03548d
Create Date: 2025-05-12 16:16:07.924962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca817d3dfeca'
down_revision = '797f6b03548d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_comment_recipe_id', 'recipe', ['recipe_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comment_recipe_id', type_='foreignkey')
        batch_op.drop_column('recipe_id')

    # ### end Alembic commands ###


# 